--- #YAML:1.0
name:               Net-STOMP-Client
version:            1.2
abstract:           STOMP object oriented client module
author:
    - Lionel Cons <lionel.cons@cern.ch>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Encode:            0
    Exporter:          0
    IO::Select:        0
    IO::Socket::INET:  0
    List::Util:        0
    Test::More:        0
    Time::HiRes:       0
    UNIVERSAL:         0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
